[colors.primary]
background = '#242424'
foreground = '#f6f3e8'

[colors.normal]
black   = '#242424'
blue    = '#5b98c2'
cyan    = '#3f9f9e'
green   = '#92a65e'
magenta = '#64619a'
red     = '#b85149'
white   = '#f6f3e8'
yellow  = '#ccaa8f'

[colors.bright]
black   = '#444444'
blue    = '#8ac6f2'
cyan    = '#70cecc'
green   = '#95e454'
magenta = '#a6a1de'
red     = '#e5786d'
white   = '#ffffff'
yellow  = '#edc4a3'
